const SK_CONTENT = [
  {
    name: 'JavaScript',
    x: -50,
    y: -70,
    iconPath: '/images/skills/javascript.png',
  },
  {
    name: 'TypeScript',
    x: -70,
    y: -50,
    iconPath: '/images/skills/typescript.png',
  },
  {
    name: 'HTML',
    x: -30,
    y: -20,
    iconPath: '/images/skills/html.png',
  },
  {
    name: 'CSS',
    x: -50,
    y: -30,
    iconPath: '/images/skills/css.svg',
  },
  {
    name: 'Tailwind CSS',
    x: -70,
    y: 20,
    iconPath: '/images/skills/tailwindcss.svg',
  },
  {
    name: 'Bootstrap',
    x: -40,
    y: 25,
    iconPath: '/images/skills/bootstrap.png',
  },
  {
    name: 'Node.js',
    x: -20,
    y: 50,
    iconPath: '/images/skills/nodejs.svg',
  },
  {
    name: 'Next.js',
    x: -40,
    y: 65,
    iconPath: '/images/skills/nextjs.png',
  },
  {
    name: 'Django',
    x: 0,
    y: 70,
    iconPath: '/images/skills/django.svg',
  },
  {
    name: 'Flask',
    x: 20,
    y: 55,
    iconPath: '/images/skills/flask.png',
  },
  {
    name: 'Plotly/Dash',
    x: 10,
    y: 30,
    iconPath: '/images/skills/plotly.png',
  },
  {
    name: 'Python',
    x: 0,
    y: -30,
    iconPath: '/images/skills/python.svg',
  },
  {
    name: 'C++',
    x: 20,
    y: -25,
    iconPath: '/images/skills/cpp.png',
  },
  {
    name: 'AWS',
    x: 70,
    y: 30,
    iconPath: '/images/skills/aws.png',
  },
  {
    name: 'Tableau',
    x: 60,
    y: 60,
    iconPath: '/images/skills/tableau.png',
  },
  {
    name: 'MySQL',
    x: 40,
    y: 20,
    iconPath: '/images/skills/mysql.png',
  },
  {
    name: 'Git',
    x: 60,
    y: 0,
    iconPath: '/images/skills/git.png',
  },
  {
    name: 'Docker',
    x: 50,
    y: -20,
    iconPath: '/images/skills/docker.svg',
  },
  {
    name: 'MATLAB ',
    x: 40,
    y: -50,
    iconPath: '/images/skills/matlab.png',
  },
  {
    name: 'Mandarin ',
    x: -20,
    y: -65,
    iconPath: '/images/skills/chinese.png',
  },
  {
    name: 'English/French ',
    x: 10,
    y: -70,
    iconPath: '/images/skills/canada.png',
  },
  {
    name: 'D3.js',
    x: -60,
    y: 55,
    iconPath: '/images/skills/d3.svg',
  },
];

export default SK_CONTENT;
